---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(scales)
library(lubridate)

df <- read.csv("lockdown.csv")
df$Date <- as.Date(df$Date,"%Y-%m-%d")

status_levels <- c("Late April", "Early May", "Late May", "Not Yet")
status_colors <- c("#0070C0", "#00B050", "#FFC000", "#C00000")
df$Lockdown.Lifted <- factor(df$Lockdown.Lifted, levels=status_levels, ordered=TRUE)


positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
    "Date"=unique(df$Date),
    "position"=rep(positions, length.out=length(unique(df$Date))),
    "direction"=rep(directions, length.out=length(unique(df$Date)))
)

df <- merge(x=df, y=line_pos, by="Date", all = TRUE)
df <- df[with(df, order(Date, Lockdown.Lifted)), ]



text_offset <- 0.1

df$month_count <- ave(df$Date==df$Date, df$Date, FUN=cumsum)
df$text_position <- (df$month_count * text_offset * df$direction) + df$position



month_buffer <- 2

month_date_range <- seq(min(df$Date) - days(month_buffer), max(df$Date) + days(month_buffer), by='day')
month_format <- format(month_date_range, '%b %d')
month_df <- data.frame(month_date_range, month_format)
```

```{r}
#### PLOT ####

timeline_plot<-ggplot(df,aes(x=Date,y=0, col=Lockdown.Lifted, label=City))
timeline_plot<-timeline_plot+labs(col="Lockdown Lifted")
timeline_plot<-timeline_plot+scale_color_manual(values=status_colors, labels=status_levels, drop = FALSE)
timeline_plot<-timeline_plot+theme_classic()

# Plot horizontal black line for timeline
timeline_plot<-timeline_plot+geom_hline(yintercept=0, 
                color = "black", size=0.3)

# Plot vertical segment lines for milestones
timeline_plot<-timeline_plot+geom_segment(data=df[df$month_count == 1,], aes(y=position,yend=0,xend=Date), color='black', size=0.2)

# Plot scatter points at zero and date
timeline_plot<-timeline_plot+geom_point(aes(y=0), size=3)

# Don't show axes, appropriately position legend
timeline_plot<-timeline_plot+theme(axis.line.y=element_blank(),
                 axis.text.y=element_blank(),
                 axis.title.x=element_blank(),
                 axis.title.y=element_blank(),
                 axis.ticks.y=element_blank(),
                 axis.text.x =element_blank(),
                 axis.ticks.x =element_blank(),
                 axis.line.x =element_blank(),
                 legend.position = "bottom"
                )

# Show text for each month
timeline_plot<-timeline_plot+geom_text(data=month_df, aes(x=month_date_range,y=-0.15,label=month_format),size=2.5,vjust=0.5, color='black', angle=0)
# Show text for each City
timeline_plot<-timeline_plot+geom_text(aes(y=text_position,label=City),size=2.5)
timeline_plot
```